### ISSUE TITLE
[Terraform] 인프라

### ISSUE THREAD

**Issue by apphia39** [PGHJteam/Project#22]
## 인프라 모듈
1. Network 모듈 생성
2. Server 모듈 생성
3. Database 모듈 생성
4. Security 모듈 생성
5. Bastion 모듈 생성

### TODO - Network 모듈 리소스 생성
- [x] vpc 
- [x] subnet(private / public)
- [x] internet gateway(public이랑 연결)
- [x] nat gateway + elastic ip(private이랑 연결)
- [x] route table(private / public)

### TODO - Server 모듈 리소스 생성
- [x] ec2 instance + key pair
- [x] ec2 security group
- [x] s3 bucket
- [x] load balancer + target group

### TODO - Database 모듈 리소스 생성
- [x] rds instance + subnet group
- [x] rds security group

### TODO - Bastion 모듈 리소스 생성
- [x] ec2 instance + key pair
- [x] ec2 security group

### TODO - Security 모듈 리소스 생성
- [x] bastion host - ec2, s3 접근 권한
- [x] server - s3 접근권한

### TODO
- [x] root에서 각 모듈 호출 및 연결
- [x] root모듈 variables -> tfvars에 정리
- [x] server용 userdata 파일 생성
- [x] bastion용 userdata파일 생성
- [x]  README 작성
