### ISSUE TITLE
[Django] users API

### ISSUE THREAD

**Issue by apphia39** [PGHJteam/Project#7]
### TODO
- [x] User 모델 커스터마이즈
- [x] admin 페이지 커스터마이즈
- [x] token authentication 구현 + refresh token blacklistapp
- [x] User Serializer 구현
- [x] request header의 access token으로부터 user정보 분리
- [x] History Serializer 구현

### Functions
1. **회원가입[POST]** {publicIP}:{port}/api/users/signup/
2. **로그인(토큰발급)[POST]** {publicIP}:{port}/api/users/signin/
3. **로그아웃(토큰삭제)[POST]** {publicIP}:{port}/api/users/signout/
4. **히스토리 조회[GET]** {publicIP}:{port}/api/users/history/
5. **토큰 리프레시[POST]** {publicIP}:{port}/api/users/token/refresh/
