### ISSUE TITLE
[Django] files API

### ISSUE THREAD

**Issue by apphia39** [PGHJteam/Project#8]
### TODO - 이미지 업로드
- [x] 업로드된 이미지를 로컬 스토리지에 저장
- [x] 로컬 스토리지에 있는 이미지를 s3로 업로드
- [x] 이미지 정보를 DB에 저장 
- [x] detection-recognition model과 연결 + 디코딩
 
### TODO - pptx 다운로드
- [x] pptx file response: pptx용 MIME-TYPE

### TODO - pptx 생성
- [x] pptx 생성 - 템플릿 적용 / 폰트 스타일 및 크기 적용 / 텍스트박스 위치 적용
- [x] 생성된 pptx를 로컬 스토리지에 저장
- [x] 로컬 스토리지에 있는 pptx 파일을  s3로 업로드
- [x] pptx 파일 정보를 DB에 저장

### Image Functions
1. **이미지 업로드 [POST]** {publicIP}:{port}/api/files/upload/images/

### Material Functions
1. **자료 생성 [POST]** {publicIP}:{port}/api/files/create/pptx/
2. **자료 다운로드 [POST]** {publicIP}:{port}/api/files/download/pptx/
